#67
select CHECK_NUM, BOOK_NUM, CHECK_OUT_DATE
from CHECKOUT
where CHECK_OUT_DATE < '2017-5-5'
order by CHECK_NUM; 

#69
select BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, BOOK_COST
from BOOK
where BOOK_SUBJECT IN ('Middleware','Cloud') AND BOOK_COST>70
order by BOOK_NUM; 

#70
select *
from AUTHOR
where AU_BIRTHYEAR between 1980 AND 1989
order by AU_ID; 

#80
SELECT count(*) as "Available Books"
FROM BOOK
WHERE BOOK_NUM NOT IN
(
	SELECT BOOK_NUM FROM CHECKOUT
    WHERE CHECK_IN_DATE IS NULL
);
 

#85
select AU_ID, 
count(BOOK_NUM) AS BOOKS_WRITTEN
from WRITES
group by AU_ID
order by BOOKS_WRITTEN desc;

#96
select AUTHOR.AU_ID, AUTHOR.AU_FNAME, AUTHOR.AU_LNAME, BOOK.BOOK_NUM, BOOK.BOOK_TITLE
from AUTHOR join WRITES ON AUTHOR.AU_ID=WRITES.AU_ID
            join BOOK ON WRITES.BOOK_NUM=BOOK.BOOK_NUM
where BOOK.BOOK_SUBJECT like 'Cloud%'
order by BOOK.BOOK_TITLE, AUTHOR.AU_LNAME;  

#98
select BOOK.BOOK_NUM, BOOK.BOOK_TITLE, 0 AS TIMES_CHECKED_OUT
from CHECKOUT join BOOK
where BOOK.BOOK_NUM not in (SELECT BOOK_NUM from CHECKOUT) 
union
select CHECKOUT.BOOK_NUM, BOOK.BOOK_TITLE,
count(CHECKOUT.BOOK_NUM) AS TIMES_CHECKED_OUT
from CHECKOUT join BOOK on CHECKOUT.BOOK_NUM=BOOK.BOOK_NUM
group by BOOK_NUM
order by TIMES_CHECKED_OUT desc, BOOK_TITLE; 

#100
SELECT AUTHOR.AU_ID, AU_LNAME, BOOK_TITLE, CHECK_OUT_DATE, PAT_LNAME
FROM PATRON JOIN BOOK ON BOOK.PAT_ID = PATRON.PAT_ID
			JOIN CHECKOUT ON CHECKOUT.BOOK_NUM = BOOK.BOOK_NUM
			JOIN WRITES ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
			JOIN AUTHOR ON WRITES.AU_ID = AUTHOR.AU_ID
WHERE AUTHOR.AU_LNAME = "Bruer"
AND PAT_LNAME = "Miles"
GROUP BY CHECKOUT.PAT_ID
ORDER BY CHECK_OUT_DATE;
 

#101
SELECT PATRON.PAT_ID, PAT_FNAME, PAT_LNAME
FROM PATRON JOIN CHECKOUT
WHERE PATRON.PAT_ID NOT IN (SELECT PAT_ID FROM CHECKOUT)
GROUP BY PAT_ID
ORDER BY PAT_LNAME, PAT_FNAME;

#105
SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST
FROM BOOK
WHERE BOOK_COST <= (SELECT min(BOOK_COST) FROM BOOK);

#106
SELECT AUTHOR.AU_ID, AU_FNAME, AU_LNAME
FROM BOOK JOIN WRITES ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
			JOIN AUTHOR ON AUTHOR.AU_ID = WRITES.AU_ID
WHERE BOOK_SUBJECT != "Programming"
GROUP BY AU_ID
ORDER BY AU_LNAME;

#108
SELECT BOOK.BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, AU_LNAME, Books_Written as "Num of Books by Author"
FROM AUTHOR JOIN WRITES ON WRITES.AU_ID = AUTHOR.AU_ID
			JOIN BOOK ON WRITES.BOOK_NUM = BOOK.BOOK_NUM
            JOIN 
            (
				SELECT AU_ID, count(BOOK_NUM) as Books_Written
				FROM WRITES
				GROUP BY AU_ID
				ORDER BY Books_Written DESC, AU_ID
			) as W ON W.AU_ID = AUTHOR.AU_ID
WHERE BOOK_SUBJECT = "Cloud"
ORDER BY BOOK_TITLE, AU_LNAME;
